### ISSUE TITLE
changing the name of the repo

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/GITRm#13]
I think we should change the name of this repo to pumi-pic as it is heading towards providing data-parallel implementations of unstructured mesh particle-in-cell functionality as opposed to GITRm specific code.  We would then create a new GITRm repo that depends on pumi-pic.

**Comment by eisungy** [comment]
I'm sorry for writing a question about XGCm. 
If pumi-pic is to be created, I guess XGCm also needs to move to using pumi-pic APIs.

**Comment by kumargp** [comment]
Can we move wiki pages and issues altogether to new GITRm ?

**Comment by cwsmith** [comment]
There were no objections at the weekly meeting. The repo will be renamed 'pumi-pic'.
